# github repository actions 페이지에 나타날 이름
name: CI/CD using github actions & docker

# event trigger
# main이나 develop 브랜치에 push가 되었을 때 실행
on:
  push:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # copy env file
      - name: Copy .env file
        run: echo "${{ secrets.NODE_ENV }}" > ./.env

      # login to docker hub
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # docker build & push to develop
      - name: Docker build & push to dev
        run: |
          docker compose build --no-cache react
          docker compose push react

      # ec2 접속 후 pull, start
      - name: Connect to EC2
        uses: appleboy/ssh-action@master
        id: deploy-dev
        with:
          host: ${{ secrets.EC2_HOST }} # EC2 퍼블릭 IPv4 DNS
          username: ubuntu 
          port: 22
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker ps
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
            sudo docker-compose down
            sudo docker-compose up -d 
            sudo docker image prune -f
